### ISSUE TITLE
Fails to run on Firefox - CORS policy and unsafe React code

### ISSUE THREAD

**Issue by Zesix** [halftheopposite/TOSIOS#11]
Steps to reproduce:

1. Clone latest
2. Open terminal and run 'yarn' then 'yarn start'
3. Point Firefox to localhost:3001, then localhost:3000 once loaded

![image](https://user-images.githubusercontent.com/10881170/68065330-aeb81f00-fcf5-11e9-8b6b-70eba8fce227.png)

**Comment by halftheopposite** [comment]
Hi @Zesix,

Thanks for reporting this issue! I'll check it out by tomorrow.
