### ISSUE TITLE
Is it possible to create a Public Server via Docker?

### ISSUE THREAD

**Issue by kibcon** [halftheopposite/TOSIOS#19]
Hi,

I was wondering if it would be okay and possible to create your own public instance of tosios on docker via google cloud?
All i read in the Readme was about localhost, thats why I ask.
If I missed anything please let me know.

Thank you in advance.

Kind regards and stay safe!

**Comment by halftheopposite** [comment]
Hello @kibcon,

Yes it should without any problems. The public demo link https://tosios-demo.herokuapp.com/ runs in a Docker image on Heroku, so it should be totally fine running on Google Cloud.

You can find more about running it on Docker here https://github.com/halftheopposite/tosios#docker-compose-.

Please do not hesitate if you have any other questions.

Aymeric

**Comment by kibcon** [comment]
Thank you very much, it worked! 
Stay healthy

Bastian
