### ISSUE TITLE
would you like to work together?

### ISSUE THREAD

**Issue by githubfan** [halftheopposite/TOSIOS#24]
I have always wanted to create a game like this. Is it possible we could work together? There are no contact details on your profile so this is the only method I could think of.

**Comment by halftheopposite** [comment]
Hello! Sorry for the late reply. I would love to help others more but I clearly not have much time to dedicate to collaborative project yet. However, I am very open about pull requests that can improve performances and gameplay. Out of curiosity: what collaboration were you thinking about?

**Comment by githubfan** [comment]
basically just helping to make the game.
