### ISSUE TITLE
Apparently it doesn't work on windows 10 if you need to test locally.

### ISSUE THREAD

**Issue by lucks** [halftheopposite/TOSIOS#34]
I had to modify certain scripts:
- @tosios/client package.json line 49 : "build": "react-scripts build" // because GENERATE_SOURCEMAP=false crash on terminal.
- package.json at line 31: "build:move": cp is only works on Unix, I try to change to copy to universal, but fail, also with robocopy, so I just remove, and copy manually, and also remove the last part on && yarn build:move.
With that I can run the project.

**Comment by lucks** [comment]
also with the code .tsx inside packages client ...
in order to fix just put on : .prettierrc

"endOfLine":"auto"

**Comment by halftheopposite** [comment]
Hi @lucks,

Thanks for bringing these issues up! I think I can find a better way of handling this that would be cross-platform. I should do a PR quite soon.

**Comment by bpkennedy** [comment]
I know this is quite a while ago, @lucks , but for anyone else who stumbles upon this - I am using the Windows Subsystem for Linux on Windows 10, installed the 20.04 ubuntu distribution, and via linux terminal was able to build and run this without any issues at all.
