### ISSUE TITLE
Menu not clickable

### ISSUE THREAD

**Issue by maxfontani** [halftheopposite/TOSIOS#36]
Hi! Thanks for the great repo! 

I have an issue: the menu box (along with its buttons/inputs) is not clickable when opened from within the match. 
It can only be closed by pressing the Esc key.
A z-index issue, I suppose.

**Comment by halftheopposite** [comment]
Hi @maxfontani, thanks for reporting this issue. I'll soon give it a check!

**Comment by maxfontani** [comment]
Found it. It was due to `pointerEvents: 'none' `
in _packages/client/src/scenes/HUD/HUD.tsx_ line 139
