### ISSUE TITLE
Installation Error [BUG]

### ISSUE THREAD

**Issue by rodrigoricky** [halftheopposite/TOSIOS#46]
![image](https://user-images.githubusercontent.com/89636767/134810451-bc009aaf-e1e9-4f60-9c02-8dd0925544cf.png)

I tried yarn and it finish downloading until I use the command, yarn build and it start giving me errors above

My OS:

Windows: 7
Bit: 32

**Comment by halftheopposite** [comment]
@rodrigoricky I do not develop on Windows, but I have the impression that on-the-fly environment variables are not supported when running commands. In this case, it appears that the `GENERATE_SOURCEMAP` env was not supported. I've updated the project and this shouldn't be an issue anymore.

**Comment by halftheopposite** [comment]
Closing issue since a lot has changed with the latest version. Feel free to reopen if the problem rises again.
