### ISSUE TITLE
Why Yarn?  Im having an issue where yarn is saying can't find a script named build? 

### ISSUE THREAD

**Issue by btaller** [halftheopposite/TOSIOS#48]
I installed yarn via their website and using 3.1.1, very new to it, not sure what im doing wrong, any help please?

Thanks!

/Node/TOSIOS# yarn build
Usage Error: Couldn't find a script named "build".

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...

**Comment by btaller** [comment]
Trying to hack it to work now, and seeing this also:

/server/src# npm update
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tosios%2fcommon - Not found
npm ERR! 404
npm ERR! 404  '@tosios/common@0.15.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

**Comment by LukeWood** [comment]
Check your yarn version it looks like the workspace is not registering

**Comment by halftheopposite** [comment]
@btaller indeed, this seems like the Yarn workspace is not understood properly. I've updated the project structure and build process and this should normally be fixed with the latest versions of Yarn.

**Comment by halftheopposite** [comment]
Closing this issue since this is mostly due to an outdated version of yarn.
