### ISSUE TITLE
In game menu items unclickable

### ISSUE THREAD

**Issue by wheresthebeefy** [halftheopposite/TOSIOS#57]
When you click on the in-game menu after starting a match, none of the items work.  Instead, it continues to show the targeting reticule, and shoots the weapon in the background (and keyboard buttons lets the player continue to move around). Only way to get out of the menu is to press ESC

**Comment by wheresthebeefy** [comment]
Saw it was resolved in another post

**Comment by halftheopposite** [comment]
> Saw it was resolved in another post

It wasn't until now, the other person had only identified the issue on their side. I just made a fix on `pointerEvents: 'all'` for the menu.

**Comment by moretarman** [comment]
Cool cool, thank you!

Just a quick note, you forgot the closing '... the file currently reads: pointerEvents: 'all,

**Comment by wheresthebeefy** [comment]
Cool cool, thank you! Just a quick note, as the code read now, it's missing an apostrophe:  pointerEvents: 'all,

**Comment by halftheopposite** [comment]
> Cool cool, thank you! Just a quick note, as the code read now, it's missing an apostrophe: pointerEvents: 'all,

That's what you get from editing directly from GitHub. Thanks for spotting that :)
